const app=document.getElementById("app");
let mood="", score=0, audio=null;
const moods=[["😔","Something feels heavy","heavy"],["😰","I'm worried or anxious","anxious"],["🧠","My mind won't stop","think"],["😵","Everything feels like too much","overwhelmed"],["😞","I'm doubting myself","doubt"],["💔","I'm hurting","hurt"],["😩","I'm drained","drained"],["😡","I'm angry","angry"],["🌫️","I'm not sure","unsure"]];
const ack={heavy:"Yeah. Something feels heavy. You don't have to explain it before we make a little room for it.",anxious:"Okay. Your mind may be running ahead right now. We don't have to solve tomorrow in the next two minutes.",think:"Ah. Your brain has opened a few too many tabs again. Let's close just one for a minute.",overwhelmed:"Okay. Let's not add another complicated decision to your day. One thing at a time.",doubt:"Yeah. Doubting yourself can make the road ahead look much bigger. We can look at it together.",hurt:"I'm sorry you're hurting. You don't have to tell me the whole story unless you want to.",drained:"You sound tired. And honestly, motivation is not always the answer to exhaustion.",angry:"Something has really got to you. You don't have to calm down on command. Let's first make some space.",unsure:"That's okay. Sometimes something feels off before we have the words for it."};
function frame(inner){app.innerHTML=`<div class="shell"><div class="top"><div class="mark"><div class="logo">AWY</div><span>AWY</span></div><div class="status">A little better, right now.</div></div><main class="stage">${inner}</main></div>`}
function home(){frame(`<section class="screen active hero"><div class="eyebrow">A small pause for you</div><h1>How are you,<br>really?</h1><p>You don't have to figure everything out right now. Just choose what feels closest.</p><div class="mood-grid">${moods.map(x=>`<button class="mood" onclick="pick('${x[2]}')"><span class="emoji">${x[0]}</span><b>${x[1]}</b></button>`).join("")}</div></section>`)}
function pick(m){mood=m; help()}
function help(){let choices={
doubt:[["💪","Help me feel stronger","Remind me what I may have forgotten.","confidence"],["🎯","Help me figure out what to do","Let's make this practical.","goal"],["👂","I just want to talk","No fixing yet.","listen"]],
think:[["🎮","Give my mind something else to do","No talking for a minute.","game"],["👂","Let me get it out","My thoughts need somewhere to go.","listen"],["🧠","Help me sort this out","One thread at a time.","talk"],["🚶","Give me a real-world reset","Get me away from the screen.","walk"]],
anxious:[["🫁","Help me calm down","Let's give your body a moment.","calm"],["🎮","Give my mind something else to do","No talking for a minute.","game"],["👂","Just listen","I need to get it out.","listen"]],
overwhelmed:[["🫁","Help me slow down","One quiet minute.","calm"],["🎯","Help me deal with one thing","Not everything. One thing.","goal"],["👂","Let me vent","I need to get it out.","listen"]],
heavy:[["🤍","Stay with me","I don't need fixing right now.","rest"],["👂","Let me talk","I want to say what's there.","listen"],["🎵","Give me a sensory pause","No thinking for a bit.","calm"]],
hurt:[["🤍","Stay with me","Just be here for a moment.","rest"],["👂","I want to tell you","I'm ready to talk.","listen"],["✍️","Write what I can't say","No need to send it.","write"]],
drained:[["🌙","Let me rest","Permission to pause.","rest"],["🎵","Give me a sensory pause","No thinking for a bit.","calm"],["🚶","Get me moving gently","A small change of scene.","walk"]],
angry:[["👂","Let me vent","No advice yet.","listen"],["🌊","Help me cool down","Let the intensity come down.","calm"],["🧠","Help me understand it","What's underneath it?","talk"]],
unsure:[["🤍","Just sit with me","We don't need to name it.","rest"],["🎮","Surprise me","Let AWY pick something.","game"],["👂","Maybe I want to talk","We'll see where it goes.","listen"]]
}[mood]||[];
frame(`<section class="screen active"><div class="eyebrow">I'm with you</div><div class="response">${ack[mood]}</div><h2 class="title">What would help right now?</h2><p class="copy">There's no wrong answer.</p><div class="choice-list">${choices.map(c=>`<button class="choice" onclick="go('${c[3]}')"><span class="icon">${c[0]}</span><span><b>${c[1]}</b><small>${c[2]}</small></span></button>`).join("")}</div><button class="back" onclick="home()">← Back</button></section>`)}
function go(type){if(["calm","rest","game","walk"].includes(type)) experience(type); else talk(type)}
function experience(type){
if(type==="game") return frame(`<section class="screen active center"><span class="tag">60-SECOND RESET</span><h2 class="title">Give your mind<br>something else to do.</h2><p class="copy">For a minute, don't solve anything. Just find the little lights.</p><div class="game" id="game"></div><p class="tiny" id="score">Found: 0</p><button class="btn soft" onclick="remind('Taking a break from a thought is not the same as ignoring your life.')">Enough for now</button></section>`)||setTimeout(dot,300);
if(type==="walk") return frame(`<section class="screen active center"><span class="tag">REAL-WORLD RESET</span><h2 class="title">Tiny mission.</h2><p class="response" style="margin:28px auto">Put your phone down and walk for five minutes.<br><br><b>Notice three things you hadn't noticed before.</b></p><button class="btn" onclick="remind('Sometimes five minutes, a little air, and a different view can change the shape of a thought.')">I'll do that</button></section>`);
let title=type==="rest"?"You don't have to fix this right now.":"Follow the light.";
let text=type==="rest"?"Stay here for a moment. Nothing to achieve.":"No need to get it perfect. Just follow along.";
frame(`<section class="screen active center"><span class="tag">A SMALL PAUSE</span><h2 class="title">${title}</h2><p class="copy">${text}</p><div class="orb-wrap"><div class="orb"></div></div><button class="btn" onclick="sound()">🎵 Soft ambient sound</button><br><button class="btn soft" onclick="remind('You are allowed to pause before you know what comes next.')">Continue</button></section>`)
}
function dot(){const g=document.getElementById("game");if(!g)return;const d=document.createElement("button");d.className="dot";d.textContent="✦";d.style.left=(5+Math.random()*84)+"%";d.style.top=(5+Math.random()*78)+"%";d.onclick=()=>{score++;document.getElementById("score").textContent="Found: "+score;d.remove();setTimeout(dot,280)};g.appendChild(d)}
function talk(type){let title="Okay. Tell me.";let prompt="You don't need to make it neat. I'm listening.";
if(type==="goal"){title="Okay. Let's make this practical.";prompt="What's the thing you're trying to achieve? One or two sentences is enough."}
if(type==="confidence"){title="Hang on. Let's be fair to you.";prompt="Tell me one thing you once found difficult but eventually handled."}
if(type==="talk"){title="Let's untangle one thread.";prompt="What's the thought that keeps coming back?"}
if(type==="write"){title="Write what you wish you could say.";prompt="You don't have to send this."}
frame(`<section class="screen active"><div class="eyebrow">No rush</div><h2 class="title">${title}</h2><p class="copy">${prompt}</p><textarea class="textarea" id="txt" placeholder="Write however it comes out..."></textarea><button class="btn" onclick="after('${type}')">${type==="listen"?"I'm done for now":"Let AWY help me think"}</button></section>`)}
function after(type){let msg=type==="goal"?"Okay. That's clearer already. Before you invest heavily, let's avoid the University of Expensive Mistakes and test the smallest version first.":type==="confidence"?"There you go. Your past self has some evidence your current self may have forgotten.":type==="listen"?"I hear you. You didn't have to make it neat or reasonable for it to matter.":"Okay. One thread, not your whole life. That's something we can work with.";
frame(`<section class="screen active"><div class="response">${msg}</div><h2 class="title">What now?</h2><div class="choice-list"><button class="choice" onclick="remind('You don’t need certainty to take a careful next step.')"><span class="icon">🎯</span><span><b>Give me one small step</b><small>Something manageable.</small></span></button><button class="choice" onclick="experience('calm')"><span class="icon">🫁</span><span><b>Give me a reset</b><small>No more thinking for a moment.</small></span></button></div></section>`)}
function remind(text){frame(`<section class="screen active center"><span class="tag">YOUR REMINDER</span><div class="reminder">${text}</div><p class="copy">Small shifts count. You don't have to leave with your whole life solved.</p><button class="btn" onclick="check()">Continue</button></section>`)}
function check(){frame(`<section class="screen active center"><div class="eyebrow">A quick check-in</div><h2 class="title">How do you feel now?</h2><p class="copy">Even a little better matters.</p><div class="choice-list" style="max-width:500px;margin:30px auto"><button class="choice" onclick="done('That's okay. You don't have to feel better just because you opened AWY.')"><span class="icon">😔</span><b>Still struggling</b></button><button class="choice" onclick="done('Good. Even a small shift is worth noticing.')"><span class="icon">🙂</span><b>A little better</b></button><button class="choice" onclick="done('I'm glad. Hold on to whatever helped.')"><span class="icon">😊</span><b>Much better</b></button></div></section>`)}
function done(t){if(audio){audio.close();audio=null}frame(`<section class="screen active center"><div style="font-size:54px">🤍</div><h2 class="title">I'm glad you checked in.</h2><p class="copy">${t}</p><button class="btn" onclick="home()">Return to AWY</button></section>`)}
function sound(){if(audio){audio.close();audio=null;return}audio=new (window.AudioContext||window.webkitAudioContext)();let o=audio.createOscillator(),g=audio.createGain();o.type="sine";o.frequency.value=174;g.gain.value=.018;o.connect(g);g.connect(audio.destination);o.start()}
home();